runtime: python39  

env_variables:
  FLASK_ENV: "production"  # Configuração para rodar o Flask em produção
  GOOGLE_CLOUD_PROJECT: "ferrous-freedom-444200-m5"  # ID do seu projeto no GCP

instance_class: F2  # Tamanho da instância (pode ser ajustado conforme necessário)

# Limitação de requisições por instância
automatic_scaling:
  min_instances: 1
  max_instances: 5  # Defina o número máximo de instâncias, dependendo do tráfego esperado

handlers:
- url: /.*  # Corresponde a todas as requisições
  script: auto  # O App Engine/Cloud Run vai executar a aplicação automaticamente